baseURL = 'https://evdb.gaiagreen.tech/'
languageCode = 'en-us'
title = 'Public domain EV database'

[taxonomies]
manufacturer = "manufacturers"

[outputs]
page = ['json']
section = ['json']
home = ['json']