baseURL = 'https://evdb.gaiacharge.com/'
languageCode = 'en-us'
title = 'EVDB - Open Electric Vehicle Database'

# Enable multilingual
defaultContentLanguage = 'en'

[taxonomies]
manufacturer = "manufacturers"

[outputs]
page = ['json']
section = ['json']
home = ['json']
